[workspace]
members = [
	"alloy-runtime",
	"alloy-core"
]

[workspace.dependencies]
serde = "1.0.147"
axum = "0.5.17"
hyper = "0.14.23" 
serde_json = "1.0.87"
tokio = "1.21.2"
futures-core = "0.3.25"
once_cell = "1.16.0"
